version: '3.8'
services:
  app:
    image: sajjikazemi/simple_ppo:1.0
    environment:
      - DISPLAY=unix${DISPLAY}
    build: 
      context: ./docker
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./..:/home/docker/simple_ppo
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    cap_add:
      - SYS_ADMIN